### ISSUE TITLE
Ugyanaz a problem

### ISSUE THREAD

**Issue by GergelyVajda** [GergelyVajda/kodol-uj#1]
Leteszteltem, és ha egy eljárás is módosít rajta (nyilt.bármi), az már elrontja az ékezetes betűket. Mellesleg az eljárások sem teszik a dolgukat.

**Comment by SzeG** [comment]
A Trim a saját bevallása szerint a vezető és a záró szóközöket távolítja el (leading and triling whitespaces).  A közepét tehát nem.
Az eljárásáok nem is eljárások, hanem függvények, vagyis rendelkeznek visszatérési értékkel. Használatuk tehát x=x.tolowercase jellegű, ellenkező esetben nem történik semmi.
A karakterkódolási hibára még nem látom a magyarázatot, szólok, ha meglesz.
